/**
 * Social package (expands /social): Instagram carousel & stories, LinkedIn
 * carousel, X/Twitter, Pinterest and Threads images. Facts only.
 */
import { credit, facts, logo, page, rel, screen } from "./common.mjs";
import { iphone, macbook } from "./devices.mjs";

const f = facts();
const P = (p) => rel(`case-study/${p}`);
const IMG = {
  crema: rel("public/videos/hero-espresso-poster.webp"),
  latte: rel("public/videos/latte-art-poster.webp"),
  cup: rel("public/videos/perfect-cup-poster.webp"),
  beans: rel("public/videos/coffee-beans-poster.webp"),
  table: rel("public/images/story/hero-long-table.jpg"),
  roaster: rel("public/images/home/story-roaster.jpg"),
};

const chromeIG = (n, total) => `
  <div style="position:absolute;left:64px;right:64px;top:60px;display:flex;justify-content:space-between;align-items:center;z-index:40">${logo(26)}<span class="mono" style="font-size:16px;opacity:.75">${String(n).padStart(2, "0")} / ${String(total).padStart(2, "0")}</span></div>
  <div style="position:absolute;left:64px;right:64px;bottom:56px;display:flex;justify-content:space-between;z-index:40"><span class="mono" style="font-size:15px;opacity:.75">@SAMSSTUDIO.DESIGN</span><span class="mono" style="font-size:15px;opacity:.75">${n < total ? "SWIPE →" : "SAVE ✦"}</span></div>`;

const big = (t, size = 96) => `<p class="serif" style="font-size:${size}px;line-height:.98;letter-spacing:-.005em">${t}</p>`;

const IG = 8;
const igSlides = [
  (n) => `<div class="frame dark grain"><div class="photo" style="background-image:url(${IMG.crema});background-position:55% 45%"></div><div class="photo" style="background:linear-gradient(180deg,rgba(23,18,14,.3),rgba(23,18,14,.15) 35%,rgba(23,18,14,.92) 80%)"></div>${chromeIG(n, IG, true)}
    <div style="position:absolute;left:64px;right:64px;bottom:160px"><div class="eyebrow" style="color:var(--cream);font-size:18px">Signature Edition · case study</div>${big("NOIR<br>CAFÉ", 190)}<p class="serif italic" style="font-size:44px;margin-top:22px;color:var(--cream)">Now in four languages, installable, and fully accessible.</p></div></div>`,
  (n) => `<div class="frame cream grain">${chromeIG(n, IG)}<div style="position:absolute;left:64px;top:170px;width:560px"><div class="eyebrow" style="font-size:18px">01 · Four languages</div>${big("English, 日本語,<br>Français, Italiano.", 72)}<p class="muted" style="font-size:24px;line-height:1.5;margin-top:24px">Every page, every price — ${f.strings ?? 641} strings translated side by side, prices in USD, EUR, JPY or GBP.</p></div>
    <div style="position:absolute;right:60px;bottom:120px">${iphone(screen("phone-ja-menu"), 380, { tilt: 4 })}</div></div>`,
  (n) => `<div class="frame dark grain">${chromeIG(n, IG, true)}<div style="position:absolute;left:64px;top:170px;width:600px"><div class="eyebrow" style="font-size:18px">02 · Offline</div>${big("The menu works<br>without signal.", 80)}<p class="muted" style="font-size:24px;line-height:1.5;margin-top:24px">An installable app with launch screens, an offline menu and cafés, and an install offer from the second visit.</p></div>
    <div style="position:absolute;right:70px;bottom:120px">${iphone(screen("phone-menu"), 360, { tilt: -4 })}</div></div>`,
  (n) => `<div class="frame dark grain"><div class="photo" style="background-image:url(${IMG.latte});opacity:.55"></div><div class="photo" style="background:linear-gradient(180deg,rgba(23,18,14,.2),rgba(23,18,14,.95) 75%)"></div>${chromeIG(n, IG, true)}<div style="position:absolute;left:64px;right:64px;bottom:170px"><div class="eyebrow" style="font-size:18px">03 · Atmosphere</div>${big("When it rains<br>in New York,<br>it rains on your phone.", 82)}<p class="muted" style="font-size:24px;line-height:1.5;margin-top:24px;max-width:820px">Light follows the city's clock; rain follows its weather — never above 8% opacity.</p></div></div>`,
  (n) => `<div class="frame paper grain">${chromeIG(n, IG)}<div style="position:absolute;left:64px;top:170px;width:880px"><div class="eyebrow" style="font-size:18px">04 · Recipe studio</div>${big("Change the grind.<br>Watch the cup change.", 78)}</div><div style="position:absolute;left:64px;right:64px;bottom:130px;border-radius:24px;overflow:hidden;box-shadow:0 30px 70px rgba(23,18,14,.25)"><img src="${screen("desktop-studio")}" style="display:block;width:100%"></div></div>`,
  (n) => `<div class="frame dark grain">${chromeIG(n, IG, true)}<div style="position:absolute;left:64px;top:170px;width:560px"><div class="eyebrow" style="font-size:18px">05 · Reservations</div>${big("A table, a pass,<br>a calendar invite.", 76)}<p class="muted" style="font-size:24px;line-height:1.5;margin-top:24px">Live availability per seat, a wallet-style pass with a QR code, and an .ics invite.</p></div><div style="position:absolute;right:70px;bottom:110px">${iphone(screen("phone-reservation"), 360, { tilt: 4 })}</div></div>`,
  (n) => `<div class="frame cream grain">${chromeIG(n, IG)}<div style="position:absolute;left:64px;right:64px;top:180px"><div class="eyebrow" style="font-size:18px">06 · For everyone</div>${big("0 axe violations.<br>In every language.", 84)}</div><div style="position:absolute;left:64px;right:64px;bottom:150px;display:grid;grid-template-columns:1fr 1fr;gap:56px 40px">${[["WCAG 2.2 AA", "keyboard, screen reader, contrast"], ["Reduced motion", "every animation has an answer"], ["320px reflow", "no sideways scroll, any language"], ["CLS 0", "nothing jumps, ever"]].map(([h, t]) => `<div style="border-top:1px solid var(--sand);padding-top:18px"><div class="serif" style="font-size:64px">${h}</div><div class="mono" style="font-size:17px;color:var(--stone);margin-top:12px">${t}</div></div>`).join("")}</div></div>`,
  (n) => `<div class="frame dark grain"><div class="photo" style="background-image:url(${IMG.table});opacity:.4"></div><div class="photo" style="background:linear-gradient(180deg,rgba(23,18,14,.5),rgba(23,18,14,.95))"></div>${chromeIG(n, IG, true)}<div style="position:absolute;left:64px;right:64px;top:360px">${big("Coffee is a ritual.<br>Design should be too.", 100)}<p class="mono" style="font-size:20px;color:var(--cream);margin-top:44px">Full case study — link in bio</p></div></div>`,
];

const STORIES = [
  ["story-01-signature", `<div class="frame dark grain"><div class="photo" style="background-image:url(${IMG.crema});background-position:55% 40%"></div><div class="photo" style="background:linear-gradient(180deg,rgba(23,18,14,.35),rgba(23,18,14,.1) 30%,rgba(23,18,14,.95) 75%)"></div><div style="position:absolute;left:72px;top:280px">${logo(34)}</div><div style="position:absolute;left:72px;right:72px;bottom:420px"><div class="eyebrow" style="font-size:22px;color:var(--cream)">New · Signature Edition</div>${big("NOIR<br>CAFÉ", 200)}<p class="serif italic" style="font-size:48px;margin-top:20px;color:var(--cream)">Four languages. Offline. For everyone.</p></div><div class="glass" style="position:absolute;left:72px;right:72px;bottom:290px;height:96px;display:flex;align-items:center;justify-content:center;color:var(--beige)"><span class="mono" style="font-size:20px">SEE THE POST ↓</span></div></div>`],
  ["story-02-languages", `<div class="frame cream grain"><div style="position:absolute;left:72px;top:280px"><div class="eyebrow" style="font-size:22px">One café, four languages</div>${big("こんにちは.<br>Bonjour.<br>Buongiorno.", 110)}</div><div style="position:absolute;left:50%;bottom:260px;transform:translateX(-50%)">${iphone(screen("phone-ja-home"), 440)}</div></div>`],
  ["story-03-offline", `<div class="frame dark grain"><div style="position:absolute;left:72px;right:72px;top:280px"><div class="eyebrow" style="font-size:22px">Installable</div>${big("Add it to your<br>home screen.", 110)}<p class="muted" style="font-size:30px;line-height:1.5;margin-top:26px">The menu and our cafés open with no connection.</p></div><div style="position:absolute;left:50%;bottom:260px;transform:translateX(-50%)">${iphone(screen("phone-menu"), 420)}</div></div>`],
  ["story-04-case-study", `<div class="frame paper grain"><div style="position:absolute;left:72px;right:72px;top:280px"><div class="eyebrow" style="font-size:22px">Behind the build</div>${big("The full<br>case study.", 130)}<p class="muted" style="font-size:30px;line-height:1.5;margin-top:26px">Research, system, motion, mockups — thirteen chapters.</p></div><div style="position:absolute;left:72px;right:72px;bottom:420px;border-radius:26px;overflow:hidden;box-shadow:0 30px 70px rgba(23,18,14,.3)"><img src="${P("behance/01-cover.png")}" style="display:block;width:100%"></div><div class="glass-cream" style="position:absolute;left:72px;right:72px;bottom:290px;height:96px;display:flex;align-items:center;justify-content:center"><span class="mono" style="font-size:20px">LINK STICKER HERE</span></div></div>`],
];

const LI = 6;
const liChrome = (n, dark) => `<div style="position:absolute;left:72px;right:72px;top:64px;display:flex;justify-content:space-between;align-items:center">${logo(24)}<span class="mono" style="font-size:16px;opacity:.7">${n} / ${LI}</span></div><div style="position:absolute;left:72px;bottom:56px">${credit(dark)}</div>`;
const LINKEDIN = [
  `<div class="frame dark grain"><div class="photo" style="background-image:url(${IMG.cup});opacity:.45"></div><div class="photo" style="background:linear-gradient(180deg,rgba(23,18,14,.4),rgba(23,18,14,.96) 70%)"></div>${liChrome(1, true)}<div style="position:absolute;left:72px;right:72px;bottom:190px"><div class="eyebrow" style="font-size:18px">Case study</div>${big("How we built a cinematic café site that's fast, accessible and in four languages.", 70)}</div></div>`,
  `<div class="frame paper grain">${liChrome(2)}<div style="position:absolute;left:72px;right:72px;top:190px"><div class="eyebrow" style="font-size:18px">The constraint</div>${big("The desktop could not change by a pixel.", 72)}<p class="muted" style="font-size:26px;line-height:1.6;margin-top:30px">Every phase was screenshot-diffed against the 1440 Figma build on six devices. Existing pages never drifted more than ${f.desktopDiff ?? "0.021%"}.</p></div><div style="position:absolute;left:50%;bottom:130px;transform:translateX(-50%)">${macbook(screen("desktop-home"), 860)}</div></div>`,
  `<div class="frame cream grain">${liChrome(3)}<div style="position:absolute;left:72px;right:72px;top:190px"><div class="eyebrow" style="font-size:18px">The approach</div>${big("Phones got their own product.", 72)}<div style="display:grid;gap:22px;margin-top:40px">${["A dock, sheets and a wallet-style reservation pass", "An atmosphere that follows New York's clock and weather", "Order ahead, reviews, an AI barista — backend-ready", "An installable app that works offline"].map((t) => `<div style="display:flex;gap:18px;align-items:baseline;font-size:26px"><span class="mono" style="font-size:16px;color:var(--ink)">→</span>${t}</div>`).join("")}</div></div></div><div style="position:absolute;left:72px;right:72px;bottom:110px;display:flex;justify-content:space-between;align-items:flex-end">${["phone-home", "phone-reservation", "phone-menu"].map((k) => iphone(screen(k), 250)).join("")}</div>`,
  `<div class="frame dark grain">${liChrome(4, true)}<div style="position:absolute;left:72px;right:72px;top:190px"><div class="eyebrow" style="font-size:18px">The architecture</div>${big("Static by default.", 76)}<div style="margin-top:40px;border-radius:20px;overflow:hidden"><img src="${P("github/architecture.png")}" style="display:block;width:100%"></div></div></div>`,
  `<div class="frame paper grain">${liChrome(5)}<div style="position:absolute;left:72px;right:72px;top:190px"><div class="eyebrow" style="font-size:18px">The results</div><div style="display:grid;grid-template-columns:1fr 1fr;gap:90px 30px;margin-top:90px">${[[f.axe ?? "0", "axe violations, all four languages"], [f.pages ?? "—", "prerendered pages"], [f.strings ?? 641, "strings translated"], ["20/20", "keyboard & focus scenarios"], [f.qaChecks ?? 227, "automated checks per phase"], [f.lighthouse?.desktopPerformance ?? "—", "Lighthouse desktop"]].map(([n, l]) => `<div class="stat"><div class="n" style="font-size:136px">${n}</div><div class="l" style="font-size:17px">${l}</div></div>`).join("")}</div></div></div>`,
  `<div class="frame dark grain">${liChrome(6, true)}<div style="position:absolute;left:72px;right:72px;top:220px"><div class="eyebrow" style="font-size:18px">The lesson</div>${big("Measure every phase. Atmosphere is expensive until you do.", 70)}<p class="muted" style="font-size:26px;line-height:1.6;margin-top:30px">A rain transition on the root element was restyling the whole page every frame on phones. Found by measuring; fixed in a line of CSS.</p></div><div style="position:absolute;left:72px;right:72px;bottom:130px;border-radius:20px;overflow:hidden;border:1px solid rgba(248,244,236,.1)"><img src="${P("motion-breakdown/05-steam-engine.png")}" style="display:block;width:100%"></div></div>`,
];

const TWITTER = [
  ["twitter-01-announcement", `<div class="frame dark grain"><div class="photo" style="background-image:url(${IMG.crema});background-position:60% 45%"></div><div class="photo" style="background:linear-gradient(90deg,rgba(23,18,14,.96) 30%,rgba(23,18,14,.2))"></div><div style="position:absolute;left:90px;top:80px">${logo(30)}</div><div style="position:absolute;left:90px;bottom:120px;width:800px"><div class="eyebrow" style="font-size:18px">Signature Edition</div>${big("A cinematic café — in four languages, installable, accessible.", 70)}</div><div style="position:absolute;left:90px;bottom:60px">${credit(true)}</div></div>`],
  ["twitter-02-responsive", `<div class="frame cream grain"><div style="position:absolute;left:90px;top:80px;width:520px"><div class="eyebrow" style="font-size:18px">One design, three rooms</div>${big("Desktop stayed exact. Phones got their own product.", 60)}</div><div style="position:absolute;left:640px;top:110px">${macbook(screen("desktop-menu"), 760)}</div><div style="position:absolute;left:1300px;top:330px">${iphone(screen("phone-menu"), 230)}</div><div style="position:absolute;left:90px;bottom:60px">${credit()}</div></div>`],
  ["twitter-03-motion", `<div class="frame dark grain"><img src="${P("motion-breakdown/07-page-transitions.png")}" style="position:absolute;inset:0;width:100%;height:100%;object-fit:cover"></div>`],
];

const PINTEREST = [
  ["pin-01-poster", `<div class="frame" style="background:#ddd2c2"><img src="${P("mockups/store-poster.png")}" style="position:absolute;left:50%;top:0;height:100%;transform:translateX(-50%)"></div>`],
  ["pin-02-objects", `<div class="frame cream grain"><div style="position:absolute;left:0;right:0;top:0;height:50%;overflow:hidden"><img src="${P("mockups/coffee-cup.png")}" style="width:150%;margin-left:-25%"></div><div style="position:absolute;left:0;right:0;bottom:0;height:50%;overflow:hidden"><img src="${P("mockups/tote-bag.png")}" style="width:150%;margin-left:-25%"></div><div class="glass-cream" style="position:absolute;left:60px;right:60px;top:50%;transform:translateY(-50%);height:110px;display:flex;align-items:center;justify-content:center">${logo(34)}</div></div>`],
  ["pin-03-phones", `<div class="frame dark grain"><div style="position:absolute;left:70px;top:90px"><div class="eyebrow" style="font-size:18px">Mobile</div>${big("Designed for<br>the hand.", 90)}</div><div style="position:absolute;left:70px;bottom:120px">${iphone(screen("phone-home"), 400, { tilt: -5 })}</div><div style="position:absolute;left:520px;bottom:200px">${iphone(screen("phone-story"), 400, { tilt: 5 })}</div></div>`],
];

const THREADS = [
  ["threads-01-typography", `<div class="frame paper grain"><div style="position:absolute;left:72px;top:72px">${logo(26)}</div><div style="position:absolute;left:72px;right:72px;top:320px">${big("Cormorant for the headline.<br>Inter for the reading.<br>Plex Mono for the price.", 76)}<p class="mono" style="font-size:22px;color:var(--ink);margin-top:44px">$6.50 · 93°C · 03:30</p></div><div style="position:absolute;left:72px;bottom:64px">${credit()}</div></div>`],
  ["threads-02-rain", `<div class="frame dark grain"><div style="position:absolute;left:72px;top:72px">${logo(26)}</div><div style="position:absolute;left:72px;right:72px;top:320px">${big("It rained in New York during testing.", 84)}<p class="muted" style="font-size:28px;line-height:1.55;margin-top:30px">The site noticed — and so did the performance budget. One CSS property later, 3 seconds of main-thread work were gone.</p></div><div style="position:absolute;left:72px;bottom:64px">${credit(true)}</div></div>`],
  ["threads-03-languages", `<div class="frame cream grain"><div style="position:absolute;left:72px;top:72px">${logo(26)}</div><div style="position:absolute;left:72px;right:72px;top:300px">${big("ゆっくりと作り、<br>シンプルに。", 100)}<p class="serif italic" style="font-size:44px;margin-top:36px;color:var(--walnut)">Made slowly. Served simply.</p><p class="mono" style="font-size:20px;color:var(--stone);margin-top:30px">NOW IN 日本語 · FRANÇAIS · ITALIANO</p></div><div style="position:absolute;left:72px;bottom:64px">${credit()}</div></div>`],
];

export const social = [
  ...igSlides.map((s, i) => ({ file: `instagram/carousel-${String(i + 1).padStart(2, "0")}`, w: 1080, h: 1350, html: page(1080, 1350, s(i + 1)) })),
  ...STORIES.map(([file, html]) => ({ file: `instagram/${file}`, w: 1080, h: 1920, html: page(1080, 1920, html) })),
  ...LINKEDIN.map((html, i) => ({ file: `linkedin/carousel-${String(i + 1).padStart(2, "0")}`, w: 1080, h: 1350, html: page(1080, 1350, html) })),
  ...TWITTER.map(([file, html]) => ({ file: `x/${file}`, w: 1600, h: 900, html: page(1600, 900, html) })),
  ...PINTEREST.map(([file, html]) => ({ file: `pinterest/${file}`, w: 1000, h: 1500, html: page(1000, 1500, html) })),
  ...THREADS.map(([file, html]) => ({ file: `threads/${file}`, w: 1080, h: 1350, html: page(1080, 1350, html) })),
];
